server:
  port: ${PORT}

company:
  product:
    id: ${PRODUCT_ID}

spring:
  cloud:
    gateway:
      routes:
        - id: main-ws
          uri: ${MAINWS_APP_URL}
          predicates:
            - Path=/add-on/api/**
          filters:
            - StripPrefix=2