company:
  name: Quart Ciphers

spring:
  application:
    name: GATEWAY-WS
  profiles:
    active: ${PROFILE:local}
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
